version: 0.2

phases:
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - aww s3 cp build s3://rocketshoes.app --recursive --acl public-read
# artifacts:
#   files:
#     - build/**
#   base-directory: build
